default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: recipe_user
  password: recipe_password
  host: db

development:
  <<: *default
  database: recipes

test:
  <<: *default
  database: recipes

production:
  <<: *default
  database: recipes
