version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://recipe_user:recipe_password@db:5432/recipes
  frontend:
    build: ./recipes-frontend
    volumes:
      - ./recipes-frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=recipe_user
      - POSTGRES_PASSWORD=recipe_password
      - POSTGRES_DB=recipes
volumes:
  bundle_cache:
  postgres_data:
