source 'https://rubygems.org'

ruby '3.2.2'

gem 'rack-cors', require: 'rack/cors'
gem 'ruby-progressbar'
gem 'graphql'

gem 'rails', '~> 7.1.2'
gem 'sprockets-rails'
gem 'puma', '>= 5.0'
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'jbuilder'
gem 'redis', '>= 4.0.1'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bootsnap', require: false
gem 'pg', '~> 1.5' # Make sure pg gem is available in all environments

group :development, :test do
  gem 'debug', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
  gem 'rubocop', require: false
end

group :development do
  gem 'web-console'
  gem 'graphiql-rails'

end

group :development, :test do
  gem 'rspec-rails', '~> 5.0.0'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '~> 4.0'
  gem 'factory_bot_rails'
  gem 'byebug', require: false
  

end

gem 'dockerfile-rails', '>= 1.6', group: :development
gem "graphiql-rails", group: :development
